crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'crm'


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('common.urls', namespace='common')),
    url(r'^', include('questions.urls', namespace='questions')),
    url(r'^knowledgebase/', include('knowledge_base.urls', namespace='knowledgebase')),
    url(r'^logout/$', views.logout, {'next_page': '/login/'}, name='logout'),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^tinymce/', include('tinymce.urls')),



]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knowledge_base/urls.py
from django.conf.urls import url
from knowledge_base import views

app_name = 'knowledge_base'


urlpatterns = [
    url(r'^$', views.knowledge_base_list, name='kb_list'),
    url(r'^add/$', views.knowledge_base_add, name='kb_add'),
    url(r'^(?P<statute_chapter>\d+)/(?P<statute_number>\d+)/view/$', views.knowledge_base_statute, name='view_knowledgebase'),
    url(r'^(?P<kb_id>\d+)/view/$', views.knowledge_base_guide, name='view_knowledgebase_guide'),
    url(r'^(?P<type>\w+)/(?P<state>\w+)/(?P<statute_chapter>\d+)/(?P<statute_number>\d+)/api/$', views.statute_as_json, name='view_api'),
    url(r'^(?P<type>\w+)/(?P<state>\w+)/(?P<kb_area>\w+)/(?P<statute_heading>\w+)/api/$', views.element_as_json, name='view_api'),
    url(r'^(?P<type>\w+)/(?P<state>\w+)/api/$', views.all_element_as_json, name='view_api_all'),
]

questions/urls.py
from django.conf.urls import url
from questions import views

app_name = 'questions'


urlpatterns = [
    url(r'^$', views.questions_list, name='list'),
    url(r'^login/$', views.login_crm, name="home"),
    url(r'^create/$', views.add_question, name='add_question'),
    url(r'^upload_file/$', views.upload_file, name='upload_files'),
    url(r'^(?P<case_id>\d+)/viewquestion/$', views.view_question, name='view_case'),
    url(r'^(?P<case_id>\d+)/edit_quesiton/$', views.edit_case, name='edit_question'),
    url(r'^(?P<case_id>\d+)/remove/$', views.remove_case, name='remove_case'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    # url(r'^comment2/add/$', views.add_comment_to_comment, name='add_2_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
    url(r'^receive-email/$', views.receive_email, name='receive_email'),
]

questions/forms.py
from django import forms
from django.forms import Textarea
from questions.models import Case
from common.models import Comment, Comment_2_Comment, LegalAidOrg, User
from questions.models import UploadFile
from django.forms.widgets import CheckboxSelectMultiple
from tinymce.widgets import TinyMCE

class DocumentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['name'].widget.attrs.update({
            'placeholder': 'Document Name'})
        self.fields['description'].widget.attrs.update({
            'placeholder': 'Document Description'})


    # name = forms.CharField()
    class Meta:
        model = UploadFile
        fields = ('name','description','file_type', 'document', )


class CaseForm(forms.ModelForm):
    # visible = forms.ModelMultipleChoiceField(queryset=LegalAidOrg.objects.all())
    def __init__(self, *args, **kwargs):
        super(CaseForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        # self.fields['visible_to'].queryset = LegalAidOrg.objects.all()
        self.fields['title'].widget.attrs.update({
            'placeholder': 'Title'})
        self.fields['related_document_name'].widget.attrs.update({
            'placeholder': 'Document Title'})
        self.fields['related_document_desc'].widget.attrs.update({
            'placeholder': 'Document Description (Optional)'})
        self.fields['issue_summary'].widget.attrs.update({
            'placeholder': 'Summary'})
        self.fields['issue_detail'].widget.attrs.update({
            'placeholder': 'Details', 'widget':'Textarea'})
        self.fields['related_cite'].widget.attrs.update({
            'placeholder': 'Case Citation - 123 So.2d 456'})

        self.fields['related_document_name'].required = False
        self.fields['rel_statute_link'].required = False
        self.fields['related_document'].required = False
        self.fields['related_document_desc'].required = False
        self.fields['issue_detail'].required = False
        self.fields['issue_summary'].required = False
        # self.fields['issue_area'].required = False
        self.fields['related_cite'].required = False
        # self.fields['visible_to'].choices = LegalAidOrg.objects.all()
        # self.fields['visible_to'].widget = CheckboxSelectMultiple()
        # self.fields["visible_to"].queryset = LegalAidOrg.objects.all()
        # issue_detail = forms.CharField(widget=forms.Textarea)
        issue_detail = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))

    class Meta:
        model = Case
        # widgets = {
        #     'issue_detail': Textarea(attrs={'size': 80, 'rows': 20, 'title':'issue_detail'})
        # }
        fields = ('title', 'issue_area', 'related_document_name',
        'rel_statute_link', 'issue_summary', 'issue_detail',
        'related_document', 'related_document_desc', 'related_cite',

        )

    def clean_name(self):
        name = self.cleaned_data['title']

        case = Case.objects.filter(name__iexact=name).exclude(id=self.instance.id)
        # if case:
        #     raise forms.ValidationError("Case Already Exists with this Name")
        # return name


class CaseCommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CaseCommentForm, self).__init__(*args, **kwargs)
        comment = forms.CharField(max_length=1000, required=True)
        self.fields['related_document'].required = False


    class Meta:
        model = Comment
        fields = ('comment', 'case', 'commented_by', 'related_document' )


class CommentCommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentCommentForm, self).__init__(*args, **kwargs)
        comment = forms.CharField(max_length=1000, required=True)

    class Meta:
        model = Comment_2_Comment
        fields = ('comment', 'commented_by')

questions/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, reverse
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from questions.models import Case, UploadFile, RelatedQuestions
from questions.forms import CaseForm, CaseCommentForm, DocumentForm, CommentCommentForm
from common.models import User, Comment, Comment_2_Comment, Practicearea, LegalAidOrg
from common.utils import PRIORITY_CHOICE, STATUS_CHOICE, INDCHOICES
from common.utils import determine_area, return_email_info, return_email_info_comment, new_post_email_info
from itertools import chain
from questions.cite_finder import cite_finder
from django.db.models import F
from questions.cite_parse import link_grabber
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout, authenticate, login
from knowledge_base.models import KB_Item
import mammoth
import nltk
from nltk.corpus import stopwords
from questions.nltk_process import nltk_process, nltk_rel_words, find_rel_questions, nltk_rel_words_email, find_rel_questions_email
import talon
import re
from crm.settings import EMAIL_ENABLED, DOMAIN_ROOT
# CRUD Operations Start

@csrf_exempt
def login_crm(request):
    print('login')
    if request.method == 'POST':
        print("POST")
        user = authenticate(username=request.POST.get('email'), password=request.POST.get('password'))
        print(user)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('/')
    return render(request, 'login.html')



@login_required
def user_profile_page(request, username):
    print(username)
    logged_in_user = request.user
    question_record = Case.objects.all()
    comments = Comment.objects.all()
    uploaded_docs = UploadFile.objects.all()
    user_record = get_object_or_404(
        User.objects.prefetch_related(), username=username)

    record = get_object_or_404(
        KB_Item.objects.prefetch_related(), statute_chapter=statute_chapter, KB_Item_number=KB_Item_number)


    user_record = User.objects.filter(username_contains=username)
    return render(request, "view_user.html", {
        'user_record': user_record,
        'logged_in_user': logged_in_user,
        'question_record':question_record,
        'comments':comments,
        'uploaded_docs':uploaded_docs,

    })

@login_required
def questions_list(request):

    # questions = Case.objects.filter(visible_to=request.user.legal_aid_org).order_by('-score').distinct()
    questions = Case.objects.all().order_by('-score').distinct()

    page_title = 'Quorum'
    question_areas = Practicearea.objects.all().distinct()
    # question_areas = Case.objects.all().values_list('issue_area', flat=True).distinct()
    counties = Case.objects.all().values_list('county', flat=True).distinct()
    orgs = LegalAidOrg.objects.all().values_list('name', flat=True).distinct()
    header = "Questions"
    page = request.POST.get('per_page')
    name = request.POST.get('name')
    specialty = request.POST.get('specialty')
    comments = Comment.objects.all()
    users = User.objects.all()
    org_filter = request.GET.get('org', '')
    state_filter = request.GET.get('state', '')
    area_filter = request.GET.get('area','')
    county_filter = request.GET.get('county','')
    searched = False
    KB_Items = KB_Item.objects.all().values_list('statute_chapter', flat=True).distinct()
    KB_Items_2 = KB_Item.objects.all()

    if len(state_filter) != 0:
        questions = Case.objects.filter(state__contains=state_filter)
        header = 'Questions in '+state_filter

    if len(org_filter) != 0:
        questions = Case.objects.filter(visible_to__name__contains=org_filter)
        header = 'Questions in '+org_filter

    if len(area_filter) != 0:
        questions = Case.objects.filter(issue_area=area_filter)
        new_area = get_object_or_404(
            Practicearea.objects.prefetch_related(), id=area_filter).area
        header = 'Questions in ' + new_area
        print(header)


    if len(county_filter) != 0:
        questions = Case.objects.filter(county__contains=county_filter)
        header = 'Questions in '+county_filter
    if name:
        questions1 = Case.objects.filter(title__contains=name)
        questions2 = Case.objects.filter(issue_detail__contains=name)
        questions3 = Case.objects.filter(issue_summary__contains=name)
        questions4 = Case.objects.filter(state__contains=name)
        questions5 = Case.objects.filter(county__contains=name)
        questions6 = Case.objects.filter(related_doc_body__contains=name)
        questions7 = Case.objects.filter(related_words__contains=name)

        questions_raw = list(
                                chain(
                                        questions1,
                                        questions2,
                                        questions3,
                                        questions4,
                                        questions5,
                                        questions6,
                                        questions7)
                                    )
        questions=[]
        for add_question in questions_raw:
            if add_question not in questions:
                questions.append(add_question)
        searched = True

    score_up = request.GET.get('score_up','')
    if len(score_up) != 0:
        print("Score Up!", score_up)
        Case.objects.filter(id=score_up).update(score=F('score') + 1)
        User.objects.filter(email=Case.objects.get(id=score_up).created_by).update(score=F('score') + 1)
        return redirect("/")

    score_down = request.GET.get('score_down','')
    if len(score_down) != 0:
        if int(Case.objects.get(id=score_down).score) > 0:
            Case.objects.filter(id=score_down).update(score=F('score') - 1)
            print("Hey ", Case.objects.get(id=score_down).created_by, " your question got down-voted")
            ## Penalize the quesiton asker
            User.objects.filter(email=Case.objects.get(id=score_down).created_by).update(score=F('score') - 1)
            ##email notification function here
            return redirect("/")

    return render(request, "questions/list.html", {
        'questions': questions,
        'area_filter': area_filter,
        'state_filter':state_filter,
        'county_filter':county_filter,
        'question_areas': question_areas,
        'per_page': page,
        'header': header,
        'comments':comments,
        'users':users,
        'searched':searched,
        'name':name,
        'counties':counties,
        'KB_Items':KB_Items,
        'KB_Items_2':KB_Items_2,
        'page_title':page_title,
        'orgs':orgs,
        'org_filter':org_filter,
    })


@login_required
@csrf_exempt
def add_question(request):
    users = User.objects.filter(is_active=True).order_by('email')
    form = CaseForm()
    page_title = 'Start Discussion'
    if request.method == 'POST':
        form = CaseForm(request.POST, request.FILES)

        if form.is_valid():
            case = form.save(commit=False)
            case.created_by = request.user
            # case.visible_to.set(request.user.legal_aid_org)
            ## Fastcase
            if len(case.related_cite) != 0:
                case.related_cite_link = link_grabber(case.related_cite)

            case.score = 0
            state = request.user.state
            case.state = request.user.state
            case.county = request.user.county
            question_text = case.issue_detail

            case.related_words = nltk_rel_words(question_text)
            User.objects.filter(id=request.user.id).update(score=F('score') + 1)
            case.save()
            print("Selected = ", case.visible_to)
            case.visible_to.add(request.user.legal_aid_org)
            form.save_m2m()
            if case.related_document:
                User.objects.filter(id=request.user.id).update(score=F('score') + 4)

                ## Need to add related_document to knowledgebase
                to_save_kb = KB_Item(
                                kb_area = case.issue_area,
                                # kb_type_id = 1,
                                related_document = case.related_document,
                                body = question_text,
                                title = case.title,
                                ## Need to add this discussion as related discussion
                                )
                to_save_kb.save()

                if str(case.related_document).split('.')[1] == 'docx':
                    print("Word doc!")
                    with open("media/"+str(case.related_document).replace(" ", "_"),
                                "rb") as docx_file:
                        result = mammoth.convert_to_html(docx_file)
                        html = result.value # The generated HTML
                    print(html)
                    case.related_doc_body = html
                    case.created_by = str(request.user)

            case.save()
            if EMAIL_ENABLED:
                for user_email in users:
                    print("Need to email a notification to", user_email.email)
                    try:
                        new_post_email_info('newpost-'+ str(case.id) + '@' + DOMAIN_ROOT, user_email.email, 'New Post in '+str(case.issue_area), str(case.issue_area), case.created_by, case.issue_detail, case.id)
                    except Exception as e:
                        print(str(e))
            if request.is_ajax():
                return JsonResponse({'error': False})
            if request.POST.get("savenewform"):
                return redirect("questions:case_add")
            else:
                # return HttpResponseRedirect(reverse('questions:list'))

templates/questions/cases_list.html
<table class="table">
    <thead>
    <tr>
        <th width="50%">
            <a href='#'>
                Name
            </a>
            <span class="caret"></span>
        </th>
        <th>
            <a href="#">
                Status
            </a>
        </th>
    </tr>
    </thead>
    <tbody>
    {% ifequal questions|length  0 %}
     <tr>
         <td class="cell">
         NO CASES FOUND!!
         </td>
     </tr>
    {% endifequal %}
    {% for case in questions %}
    <tr>
        <td class="cell">
            <a class="cell parentname" id="{{ case.id }}">
                {{ case.name }}
            </a>
        </td>
        <td class="cell parentstatus">
            {{ case.status }}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

templates/questions/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}

    <div class="right_col" role="main">
      <div class="col-md-8 col-sm-6 col-xs-12" style="width:95%">



      </div>
      <center>
          {% if area_filter %}
          <h3>{{header}} <a href="/" id="filter_clear" class="btn btn-round btn-default">Clear</a></h3></h3>
          {% endif %}
          {% if searched == True %}
          <h3>Search terms: {{name}} <a href="" id="filter_clear" class="btn btn-round btn-default">Clear</a></h3>
          {% endif %}
      </center>
      <br>

  <div class="container  text-left">
  <div class="col-md-12 col-sm-12 col-xs-12" >

  <form id="questions_filter" method="POST" action="" >{% csrf_token %}
  <!-- <div class="col-sm-12"> -->

    <div class="input-group">
      <input type="text" class="form-control" name="name" value="{{request.POST.description}}">
      <span class="input-group-btn"><button style="" type="submit" id="filter_click" class="btn btn-round btn-default"><i class="fa fa-search"></i></button>
        </span>

    </div>

    </form>


        {% for case in questions %}

        {% if case.name == 'No Associated Case' %}
        {% else %}

        <div class="x_panel">
          <div class="x_title">
            <h4><a href="{% url 'questions:view_case' case.id %}">{{ case.title }}</a><small></small>
            <ul class="nav navbar-right panel_toolbox">

              <li><a href="?score_up={{ case.id }}"><i class="fa fa-thumbs-up"></i></a></li>
              <li>{{case.score}}</li>
              <li><a href="?score_down={{ case.id }}"><i class="fa fa-thumbs-down" ></i></a></li>
              {% if case.related_document %}
              <li><i class="fa fa-file"></i></li>
              {% endif %}

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-map-marker"></i></a>
                <ul class="dropdown-menu" role="menu">


                  <li style="background:#ededed"> &nbsp &nbsp Jurisdiction:
                  </li>
                  <li><a href="?county={{user.county}}">{{case.created_by.county}}</a>
                  </li>
                  <li><a href="?state={{ user.state }}">{{case.created_by.state}}</a>
                  </li>


                </ul>
              </li>
              <li> </li>
              <!-- <li><a class="close-link"><i class="fa fa-close">Hide</i></a> -->
              </li>
              <!-- <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li> -->
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <h4><a href="{% url 'questions:view_case' case.id %}">{{ case.issue_detail|truncatechars:200|safe }}</a></h4>
            <p>Practice Area:
              <a href="?area={{ case.issue_area.id }}">
                {{ case.issue_area }}</a>
            </p>
            <p>Started by:

                <a href="/user/{{case.created_by.username}}/view">{{ case.created_by.username }}</a>
                <p>{{case.created_by.legal_aid_org}}</p>
            </p>
          </div>
        </div>


        {% endif %}
        {% endfor %}




      <!-- <div class="panel-content"> -->

          {% ifequal questions|length 0 %}
            <h4 class="text-center">No discussions yet.</h4>
            <!-- <h4 class="text-center">  <button type="submit" class="btn btn-round btn-default">
              <a href="/create"><i class="fa fa-comments"></i> Start one.</a></button>
            </h4> -->
          {% endifequal %}

        </div>
      </div>
    </div>
  </div>
  <!-- questions_list ends here -->
</div>
<!-- main_container ends here -->
{% endblock %}
{% block js_block %}
  <script src="{% static 'js/questions/questions.js' %}"></script>
{% endblock js_block %}

templates/questions/view_case.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
  <!-- CASE VIEW STARTS -->

      <div class="right_col" role="main">



          <div class="x_panel">
            <div class="x_title" style="color:black">

              <h4>{{ case_record.title }}



                <div class="pull-right" style="margin-right:10px">
                  <a href="?score_up={{ case_record.id }}"><i class="fa fa-thumbs-up"></i></a>
              &nbsp{{case_record.score}} &nbsp
              <a href="?score_down={{ case_record.id }}"><i class="fa fa-thumbs-down" ></i></a></div></h4>
            </div>


                  {% if case_record.created_by.username == logged_in_user.username %}
                  <div class="pull-right" style="margin-right:50px">
                  <div class="dropdown">


                        <span class="fa fa-edit" id="dropdownMenu1" data-toggle="dropdown"></span>

                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

                        <li><a href="{% url 'questions:edit_question' case_record.id %}" id="edit_case">EDIT</a></li>
                        <li class="delete_case" ><a href="{% url 'questions:remove_case' case_record.id %}" id="remove_case">REMOVE</a></li>
                      </ul>
                    </div>
                    </div>
                {% endif %}
            <div class="panel-content" id="datashow">
              <div class="row marl">


              </div>
              <div class="row marl">

                <div class="col-md-12" style="color:black">
                  <div class="filter_col col-md-8 col-sm-12">
                    <!-- <div class="form-group"> -->

                      <div class="case_field" id="case_status" data-name="name">{{ case_record.issue_detail|safe|urlizetrunc:20 }}</div>
                    </div>
                    <div class="filter_col col-md-4">
                      <!-- <div class="form-group"> -->
                      {% if case_record.rel_statute_link_id %}
                        <label class="case_field_label" for="id_status" data-name="name">Related KB Item</label>
                        <div class="case_field" id="case_status" data-name="name">
                          {% for item in KB_Items_2 %}
                          {% if case_record.rel_statute_link_id == item.id %}
                          <a href="{% url 'knowledge_base:view_knowledgebase_guide' case_record.rel_statute_link_id %}">{{ item }}</a>
                          {% endif %}
                          {% endfor %}

                          </div>
                          {% if case_record.rel_statute_link.kb_type == 'element' %}
                          <a href="{% url 'knowledge_base:view_knowledgebase_guide' case_record.rel_statute_link.id  %}">{{ case_record.rel_statute_link }}</a></div>
                          {% endif %}
                        {% endif %}
                        <label class="case_field_label" for="id_status" data-name="name">Area</label>
                        <div class="case_field" id="case_status" data-name="name">{{ case_record.issue_area }}</div>
                        <label class="case_field_label" for="id_status" data-name="name">Author:</label>

                        <div class="case_field" id="case_status" data-name="name"><a href="/user/{{case_record.created_by.username}}/view">{{ case_record.created_by.username }}</a></div>



                </div>
                {% if case_record.related_cite %}
                      <label class="case_field_label" for="id_status" data-name="name">Case Cite Found:</label><br>
                      <a href="{{case_record.related_cite_link}}"><button class="btn btn-round">{{ case_record.related_cite }}</button></a>

                    <!-- <iframe class="col-md-12" src="{{case_record.related_cite_link}}"></iframe> -->
                </div>
                {% endif %}
              </div>
              <br>


          </div>
          </div>

          {% if case_record.related_document %}
          <div class="x_panel">
            <div class="x_title">
                RELATED DOCUMENTS:
                  <a href="https://s3.amazonaws.com/finch-bucket/media/{{case_record.related_document}}">
                    <button><i class="fa fa-download"></i>
                      {% if case_record.related_document_name %}
                      {{case_record.related_document_name}}
                      {% else %}
                      Download
                      {% endif %}
                    </button></a>
            </div>
            {% if pdf_odj %}
            <div  style="margin-left:1%; margin-right:1%; height:500px" id="motion_pdf">
              <div>

              </div>
              </div>
              {% endif %}

            {% if case_record.related_doc_body %}
            {{case_record.related_doc_body|safe}}
            {% endif %}
            </div>
          {% endif %}


            <div class="x_panel">


              <form id="comment_form" method="POST" enctype="multipart/form-data">{% csrf_token %}
              <!-- <div class="col-md-6 col-xs-12"> -->


                <div class="compose-body">
                  <div id="alerts"></div>



                  <!-- <input id="id_comments" name="comment" class="editor-wrapper"/> -->
                  <textarea contenteditable="true" class="editor-wrapper" id="id_comments" name="comment" placeholder="Submit Your Comments Here">


                  </textarea>
                  <span><i id="CommentError" style="display:none; color:red"></i></span>
                  <input type="hidden" value="{{case_record.id}}" name="caseid">
                </div>
                <div class="btn-toolbar editor" data-role="editor-toolbar" data-target="#editor">

                  <div class="btn-group">
                    <input name="file_upload" type="file">
                  </div>

                </div>
                <div class="compose-footer">
                  <!-- <button id="comment_submit" type="submit" class="btn btn-sm btn-success" type="button">Send</button> -->
                  <button id="comment_submit" type="submit" class="btn btn-round btn-default btn-block" type="button">ANSWER</button>
                </div>
              <!-- </div> -->

              </form>
              </div>
              <div class="x_panel">
                <div class="x_title">
                  {% if comments.count == 1 %}
                  {{comments.count}} Comment
                  {% else %}
                  {{comments.count}} Comments
                  {% endif %}
                </div>
              <!-- </div> -->
                {% for comment in comments %}
                <div class="x_panel">

                  <p class="message">{{ comment.comment|urlizetrunc:30|safe }} </p>
                  {% if comment.related_document %}
                  <p><a href="https://s3.amazonaws.com/finch-bucket/media/{{comment.related_document}}">
                    <button><i class="fa fa-download"></i>

                    Download

                  </button>
                  </a></p>
                  {% endif %}
                  <p><span><a href="/user/{{comment.commented_by}}/view">{{ comment.commented_by }}</a></span>


                  <span class="time pull-right right-container">{{ comment.commented_on }}</span></p>
                  <a href="?comment_score_up={{ comment.id }}"><span class="fa fa-thumbs-up"></span></a>
                  {{comment.score}}
                  <a href="?comment_score_down={{ comment.id }}"><span class="fa fa-thumbs-down" ></span></a>
                  <br>



                  {% if comments_2_comments %}


                  {% for comment_2 in comments_2_comments %}
                  {% if comment_2.orig_comment_id == comment.id %}

                    <div class="x_panel pull-right" style="max-width:85%; background-color:#F7F7F7">
                  <p class="message">{{comment_2.comment|urlizetrunc:30}}</p>
                  {% for user in users %}
                  {% if comment_2.commented_by_id == user.id %}
                    <span class="pull-right"><a href="/user/{{user.username}}/view">{{ user.username }}</a></span>
                    <br>
                    <span class="pull-right">{{ comment_2.commented_on }}</span>
                    {% endif %}
                    {% endfor %}

                </div>
                  {% endif %}
                  {% endfor %}
                  {% endif %}



                    {% if case_record.created_by == logged_in_user.username %}

            <form id="comment_2_form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                  <div class="compose-body x_panel pull-right" style="max-width:85%; background-color:#F7F7F7">
                    <div id="alerts"></div>
                    <textarea contenteditable="true" class="editor-wrapper" id="id_comments" name="comment" placeholder="Reply to {{ comment.commented_by }}'s Answer">
                    </textarea>
                    <span><i id="CommentError" style="display:none; color:red"></i></span>
                    <input type="hidden" value="{{comment.id}}" name="commentid"><input type="hidden" value="{{case_record.id}}" name="case_id_id">
                  <!-- </div>
                  <div class="compose-footer"> -->
                    <button id="comment_submit" type="submit" class="btn btn-sm btn-success btn-block" type="button">Reply</button>
                  </div>
                </form>
                {% endif %}
                </div>

                {% endfor %}
              </div>

          <script src="{% static 'js/questions/view_case.js' %}"></script>
          <script src="{% static 'js/questions/create_case.js' %}"></script>
            <script>PDFObject.embed("https://s3.amazonaws.com/finch-bucket/media/{{case_record.related_document}}", "#motion_pdf");</script>
            <script>PDFObject.embed("https://s3.amazonaws.com/finch-bucket/media/{{comment.related_document}}", "#comment_pdf");</script>



{% endblock %}
{% block js_block %}

{% endblock js_block %}