common/urls.py
from django.conf.urls import url
from common import views
from django.contrib.auth import views as auth_views
from django.urls import path


app_name = 'common'

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^login/$', views.login_crm, name="home"),
    url(r'^upload_file/$', views.upload_file, name='upload_files'),
    path('<username>/view/', views.user_profile_page, name='view'),
    path('<username>/edit/', views.edit_user, name='edit'),
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'crm'


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('common.urls', namespace='common')),
    url(r'^', include('questions.urls', namespace='questions')),
    url(r'^knowledgebase/', include('knowledge_base.urls', namespace='knowledgebase')),
    url(r'^logout/$', views.logout, {'next_page': '/login/'}, name='logout'),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^tinymce/', include('tinymce.urls')),



]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knowledge_base/urls.py
from django.conf.urls import url
from knowledge_base import views

app_name = 'knowledge_base'


urlpatterns = [
    url(r'^$', views.knowledge_base_list, name='kb_list'),
    url(r'^add/$', views.knowledge_base_add, name='kb_add'),
    url(r'^(?P<statute_chapter>\d+)/(?P<statute_number>\d+)/view/$', views.knowledge_base_statute, name='view_knowledgebase'),
    url(r'^(?P<kb_id>\d+)/view/$', views.knowledge_base_guide, name='view_knowledgebase_guide'),
    url(r'^(?P<type>\w+)/(?P<state>\w+)/(?P<statute_chapter>\d+)/(?P<statute_number>\d+)/api/$', views.statute_as_json, name='view_api'),
    url(r'^(?P<type>\w+)/(?P<state>\w+)/(?P<kb_area>\w+)/(?P<statute_heading>\w+)/api/$', views.element_as_json, name='view_api'),
    url(r'^(?P<type>\w+)/(?P<state>\w+)/api/$', views.all_element_as_json, name='view_api_all'),
]

questions/urls.py
from django.conf.urls import url
from questions import views

app_name = 'questions'


urlpatterns = [
    url(r'^$', views.questions_list, name='list'),
    url(r'^login/$', views.login_crm, name="home"),
    url(r'^create/$', views.add_question, name='add_question'),
    url(r'^upload_file/$', views.upload_file, name='upload_files'),
    url(r'^(?P<case_id>\d+)/viewquestion/$', views.view_question, name='view_case'),
    url(r'^(?P<case_id>\d+)/edit_quesiton/$', views.edit_case, name='edit_question'),
    url(r'^(?P<case_id>\d+)/remove/$', views.remove_case, name='remove_case'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    # url(r'^comment2/add/$', views.add_comment_to_comment, name='add_2_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
    url(r'^receive-email/$', views.receive_email, name='receive_email'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <link rel="icon" type="image/png" href="" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>Finch{% block title %}{% endblock %}</title>
      <link rel="icon" type="image/png" href="/static/images/greyfinch.png">

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <!-- <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet"> -->
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
      <script src="{% static 'js/pdfobject.js' %}"></script>
      <script src="{% static 'js/annotator-full.min.js' %}"></script>
      <script src="{% static 'js/index.js' %}"></script>
      <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
                integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
                crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col menu_fixed {% block sidebar_class %} {% endblock sidebar_class %}">


              {% if 'knowledgebase' in request.get_full_path %}
              {% include "sidebar3.html" %}
              {% else %}
              {% include "sidebar.html" %}
              {% endif %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "nav_menu2.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}


        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="{% static 'js/text-select.js' %}"></script>
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/custom.js"></script>

      <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

      <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
      <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
      <script src="{% static 'js/index.js' %}"></script>
      <script src="{% static 'js/annotator-full.min.js' %}"></script> -->
    {% endblock body %}
  </body>
</html>

templates/edit-user.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<div class="right_col" role="main">



    <div class="x_panel">
      <div class="x_title">
        <h3>{{page_title}}</h3>
  </div>


  <form method="POST" enctype="multipart/form-data">{% csrf_token %}

          {{form}}

          <br>

                  <button type="submit" class="btn btn-sm btn-success btn-block" type="button">SAVE</button>


      <br clear="all">
      <input type="hidden" id="save_new_form" name="savenewform">

  </form>
  <br><br><br>
{% endblock %}
{% block js_block %}
  <script src="{% static 'js/questions/create_case.js' %}"></script>
  <script type="text/javascript">
    $(function () {
     var date = new Date();
     var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
      $('#datepicker1').datetimepicker({
          'format': 'YYYY-MM-DD',
          minDate: today
      }).attr('readonly', 'true')
    });

    $(".savenew").on('click', function(e){
      e.preventDefault()
      $("#save_new_form").val('true')
      $('#submitForm').submit()
    });
  </script>
{% endblock js_block %}

templates/markdown_editor.html
<script src="{{ STATIC_URL }}js/jquery.selection.js"></script>
<script src="{{ STATIC_URL }}js/quora.markdown.js"></script>

<div class="markdown">
  <div class="modal fade" id="markdown_help">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Help</h4>
        </div>
        <div class="modal-body">
          <p>You can learn more about markdown syntax <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">here</a>.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-sm" ref="header"><span class="glyphicon glyphicon-header"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="bold"><span class="glyphicon glyphicon-bold"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="italic"><span class="glyphicon glyphicon-italic"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="list"><span class="glyphicon glyphicon-list"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="link"><span class="glyphicon glyphicon-link"></span></button>
  </div>
</div>
<script>$(function(){$("#{{ textarea }}").markdown();});</script>

templates/nav_menu.html
{% load static %}
<!-- <div class="collapse navbar-toggleable-sm pull-xs-left pull-md-right" id="main-menu"> -->
<style>
.navbar {
  min-height: 50px;
}
</style>




        <nav class="navbar navbar-default navbar-fixed-top" style="margin-right:5px">

          <a class="navbar-brand dropdown-toggle hidden-xs" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">LEVEL</a>
                    <a class="navbar-brand visible-xs dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">LEVEL<span class="caret"</span></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'questions:add_question' %}">Ask a Question</a></li>
                      <li><a href="{% url 'questions:list' %}">Questions</a></li>
                      <li><a href="/"></span>Home</a></li>
                      <li><a href="/{{user.id}}/view">Profile</a></li>
                      <li><a href="{% url 'logout' %}">Logout</a></li>

                        <li><form id="questions_filter" method="POST" action="" >{% csrf_token %}
                              <input type="text" class="" placeholder="search" name="name" value="{{request.POST.description}}">

                                  <button class="btn-xs btn-round" style="text-center"
                                   id="filter_click" type="submit"><span class="fa fa-search"/></button></form></li>




                    </ul>
                  <!-- </span> -->

                  <!-- <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class='caret'>
                  </a> -->

                <!-- </div> -->
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse"  id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                      <li><a href="{% url 'questions:add_question' %}">Ask a Question</a></li>
                      <li><a href="{% url 'questions:list' %}">Questions</a></li>
                      <li><a href="/"></span>Home</a></li>
                      <li><a href="{% url 'logout' %}">Logout</a></li>
                    </ul>



                <form class="pull-right" id="questions_filter" method="POST" action="" >{% csrf_token %}

                        <input type="text" class="form-group" placeholder="search" name="name" value="{{request.POST.description}}">

                            <button class="btn-sm btn-round" style="text-center"
                             id="filter_click" type="submit"><span class="fa fa-search"  id="filter_click" type="submit"></span></button>


                </form>


        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

templates/person_add.html
<form method="POST">
  {{form.as_table}}
  <button type="submit" value="Submit">Submit</button>
</form>

templates/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="/" class="site_title"> &nbsp <img src="/static/images/greyfinch.png" style="width:26px"> Finch KM</a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">


  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section"  style="text-center">

      {% if 'viewquestion' in request.get_full_path %}

      <ul class="nav side-menu"  style="text-center">
        <!-- <a class="site_title" > {{page_title}}</a> -->
        {% if results_x %}
        <li><a><i class="fa fa-sitemap"></i> Related Discussions:<span class=""></span></a>
          <ul class="nav child_menu">

          {% for q in results_x.distinct %}
          {% for z in q.related_questions.all %}
          <li><a href="/{{ z.id }}/viewquestion/">{{z.title}}</a></li>
          {% endfor %}

          {% endfor %}
        </ul>
        {% endif %}



      </ul>

      {% else %}

      <ul class="nav side-menu"  style="text-center">
        <!-- <a class="site_title" > {{page_title}}</a> -->
        <li><a href="/create" color="black"><i class="fa fa-comments"></i>Start Discussion<span class=""></span></a>
        {% if '?county' in request.get_full_path %}
        <li><a><i class="fa fa-map-marker"></i>{{county_filter}}<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">


              <li><a href="/">Clear Filter</a></li>


          </ul>

        {% elif '?state' in request.get_full_path %}
        <li><a><i class="fa fa-map-marker"></i>{{state_filter}}<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">

              {% for county in counties %}
              <li><a href="/?county={{ county }}">{{county}}</a></li>
              {% endfor %}
          </ul>

          {% else %}
          <li><a><i class="fa fa-map-marker"></i>All Jurisdictions <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">

                {% for county in counties %}
                <li><a href="/?county={{ county }}">{{county}}</a></li>
                {% endfor %}
            </ul>
          </li>
          {% endif %}

          {% if 'org' in request.get_full_path %}
          <li><a><i class="fa fa-map-marker"></i>{{org_filter}}</a>
            <ul class="nav child_menu">

                  <li><a href="/">Clear Filter</a></li>
            </ul>
          </li>
          {% else %}
          <li><a><i class="fa fa-map-marker"></i>All Organizations <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">

                {% for org in orgs %}
                <li><a href="/?org={{ org }}">{{org}}</a></li>
                {% endfor %}
            </ul>
          </li>
          {% endif %}
        <!-- </li> -->

        {% if request.get_full_path == '/' %}
        <li><a><i class="fa fa-cubes"></i> Areas <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">

            {% for quest in question_areas %}
            <li><a href="/?area={{ quest.id }}">{{quest}}</a></li>
            {% endfor %}

          </ul>

          {% elif '?area' in request.get_full_path %}
            <li><a><i class="fa fa-desktop"></i>{{header}} <span class="fa fa-chevron-down"></span></a>

        </li>
        {% endif %}
        <!-- <li><a style="" href="{% url 'questions:list' %}"><i class="fa fa-table"></i> View All Discussions</a>

        </li> -->

        <li><a href="/knowledgebase"><i class="fa fa-sitemap"></i> Knowledge Base</a>

      </ul>
      {% endif %}
    </div>

  </div>

  <div class="sidebar-footer hidden-small">

  </div>
  <!-- /menu footer buttons -->
</div>

templates/sidebar3.html
<div class="left_col scroll-view" >
  <div class="navbar nav_title" style="border: 0;">
    <a href="/" class="site_title"> &nbsp <img src="/static/images/greyfinch.png" style="width:26px"> Finch KM</a>
  </div>

  <div class="clearfix">

  </div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">

  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">



      <ul class="nav side-menu">

        <!-- <a class="site_title"  style="text-center">{{page_title}}</a> -->
        <li ><a style="" href="{% url 'questions:list' %}"><i class="fa fa-table"></i> View All Discussions</a>

        </li>

        <li><a href="{% url 'knowledge_base:kb_add' %}"><i class="fa fa-comments"></i>Create KB Item<span class=""></span></a>
        <li><a href="/knowledgebase"><i class="fa fa-sitemap"></i> Knowledge Base<span class=""></span></a>
                    <!-- <ul class="nav child_menu">
                      <li><a href="/knowledgebase">View All<span class="fa fa-book"></span></a>
                      {% for stat in statutes %}

                        <li><a>{{stat}}<span class="fa fa-chevron-down"></span></a>
                          <ul class="nav child_menu">
                            {% for stat_1 in statutes_2 %}
                            {% if stat_1.chapter == stat %}

                            <li class="sub_menu">
                              <a data-toggle="tooltip" data-placement="top" title="{{stat_1.heading}}" href="/knowledgebase/{{stat_1.chapter}}/{{stat_1.statute_number}}/view/">
                              {{stat_1.statute_number}}</a>
                            </li>

                            {% endif %}
                            {% endfor %}
                          </ul>
                        </li>

                      {% endfor %}
                    </ul>
                  </li>
      </ul> -->
    </div>

  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <!-- <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a> -->
  </div>
  <!-- /menu footer buttons -->
</div>

templates/view_user.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
  <!-- CASE VIEW STARTS -->
  <div class="right_col" role="main">



      <div class="x_panel">
        <div class="x_title">


              <center><h3>{{ user_record.username }}</h3>
                <h4>Score = {{user_record.score}}
              </center>
            </div>

                  {% if user_record.email == logged_in_user.email %}
                  <div class="pull-right">
                  <div class="dropdown">

                      <p style="margin-top: -10px; margin-right:10px" id="dropdownMenu1" role="button" aria-haspopup="true" data-toggle="dropdown">Edit Profile
                        <span class="fa fa-plus" id="dropdownMenu1" data-toggle="dropdown"></span></p>

                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

                        <li><a href="{% url 'common:edit' user_record.username %}" id="edit_case">EDIT</a></li>

                      </ul>
                    </div>
                    </div>
                {% endif %}
            <div class="panel-content" id="datashow">
              <div class="row marl">

                <div class="col-md-12">
                  <div class="filter_col col-md-6">
                    <!-- <div class="form-group"> -->

                      <div class="case_field" id="case_status" data-name="name">{{ user_record.email }}</div>
                      <div class="case_field" >{{ user_record.county }}, {{user_record.state}}</div>
                      <div class="case_field" ><a href="{{ user_record.legal_aid_org.website_url }}">{{user_record.legal_aid_org}}</a></div>

                    </div>




              </div>
                <div class="col-md-12">
                  <div class="filter_col col-md-12">

                    <!-- <div class="form-group"> -->


                    <!-- </div> -->

                    <br>
                  </div>

                <div class="col-md-6">


                  <div class="filter_col col-md-4">
                    {% if user_record.issue_area %}
                    <!-- <div class="form-group"> -->
                      <label class="case_field_label" for="id_account" data-name="name">Area: <a href="">{{ user_record.issue_area }}</a></label>
                    <!-- </div> -->
                    {% endif %}
                  </div>
                  <div class="filter_col col-md-3">
                    {% if user_record.related_statute %}
                    <!-- <div class="form-group"> -->
                      <label class="case_field_label" for="id_account" data-name="name">Statute: <a href="{{user_record.rel_statute_link}}">{{ user_record.related_statute }}</a></label>
                    <!-- </div> -->
                    {% endif %}
                  </div>

                </div>


                <br>
              </div>
            </div>
          </div>
          </div>


          <div class="x_panel">
            <div class="x_title">
          <h4>Documents:
            {% if user_record.email == logged_in_user.email %}
            <div class="pull-right"><a href="/upload_file"><button class="btn btn-round"><i class="fa fa-plus"></i></button></a></div>
            {% endif %}
            </h4>
        </div>

        <div class="panel-content" style="margin-left:1%; margin-right:1%">
          <table class="table table-borderless table-striped table-condensed" id="multiselect" >
            <thead>
              <tr>

                <th width="20%" style="text-align:left;">Title</th>
                <th width="20%" style="text-align:left;">Description</th>
                <th width="10%" style="text-align:left;">Link</th>

              </tr>
            </thead>
        {% for question in question_record %}

          {% if question.created_by == user_record.username %}
          {% if question.related_document %}
          <tr class="case_row{{question.id}}" style="text-align:left;">

            <td><a>{{question.related_document_name}}</a></td>
            <td><a>{{question.related_document_desc}}</a></td>
            <td><a href="https://s3.amazonaws.com/finch-bucket/media/{{question.related_document}}"><button class="btn btn-sm btn-success">Download</button></a></td>
          </tr>
            {% endif %}
          {% endif %}
      {% endfor %}

      {% for doc in uploaded_docs %}

        {% if doc.created_by == user_record.email %}

        <tr class="case_row{{question.id}}" style="text-align:left;">

          <td><a>{{doc.name}}</a></td>
          <td><a>{{doc.description}}</a></td>
          <td><a href="https://s3.amazonaws.com/finch-bucket/media/{{doc.document}}"><button class="btn btn-sm btn-success">Download</button></a></td>
        </tr>

        {% endif %}
    {% endfor %}
    {% for comment in comments %}
      {% if comment.related_document %}
      {% if user_record.id == comment.commented_by_id %}
      <tr class="case_row{{question.id}}" style="text-align:left;">
        <td><a>Comment: </a></td>
        <td><a>{{comment.comment|truncatechars:40}}</a></td>
      <td><a href="/media/{{comment.related_document}}"><button class="btn btn-sm btn-success">Download</button></a></td>
      </tr>
      {% endif %}
      {% endif %}
    {% endfor %}
    </table>
        </div>

        </div>


          <div class="x_panel">
            <div class="x_title">
          <h4>Discussions:<h4>

        </div>
        <div class="panel-content" style="margin-left:1%; margin-right:1%">
          <table class="table table-borderless table-striped table-condensed" id="multiselect" >
            <thead>
              <tr>

                <th width="20%" style="text-align:left;">Discussion Posted</th>
                <th width="20%" style="text-align:left;">Area</th>
              </tr>
            </thead>
              <tbody>

  {% for question in question_record %}

    {% if question.created_by == user_record %}
    <tr class="case_row{{question.id}}" style="text-align:left;">

      <td><a href="{% url 'questions:view_case' question.id %}">{{question.title}}</a></td>
      <td><a href="">{{question.issue_area}}</a></td>
    </tr>


    {% endif %}
{% endfor %}
  </tbody>

</div></div>
</div>
</div>



</div></div>
</div>
</div>




    <div class="panel-content" style="margin-left:1%; margin-right:1%">
      <table class="table table-borderless table-striped table-condensed" id="multiselect" >
        <thead>
          <tr>

            <th width="20%" style="text-align:left;">Comments</th>

          </tr>
          <tbody>

{% for comment in comments %}
{% if comment.commented_by_id == user_record.id %}

<tr class="" style="text-align:left;">

  <td><a href="{% url 'questions:view_case' comment.case_id %}">{{comment.comment|truncatechars:100}}</a></td>

</tr>
{% endif %}

{% endfor %}
</div></div>
</div>


{% endblock %}
{% block js_block %}
  <script src="{% static 'js/questions/view_case.js' %}"></script>
  <script src="{% static 'js/questions/create_case.js' %}"></script>
    <script>PDFObject.embed("https://s3.amazonaws.com/finch-bucket/media/{{user_record.related_document}}", "#motion_pdf");</script>
{% endblock js_block %}